# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/winch/0x590/c++/interpretator6502

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/winch/0x590/c++/interpretator6502

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/winch/0x590/c++/interpretator6502/CMakeFiles /home/winch/0x590/c++/interpretator6502/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/winch/0x590/c++/interpretator6502/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named int6502

# Build rule for target.
int6502: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 int6502
.PHONY : int6502

# fast build rule for target.
int6502/fast:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/build
.PHONY : int6502/fast

src/draw.o: src/draw.cpp.o

.PHONY : src/draw.o

# target to build an object file
src/draw.cpp.o:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/draw.cpp.o
.PHONY : src/draw.cpp.o

src/draw.i: src/draw.cpp.i

.PHONY : src/draw.i

# target to preprocess a source file
src/draw.cpp.i:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/draw.cpp.i
.PHONY : src/draw.cpp.i

src/draw.s: src/draw.cpp.s

.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.cpp.s:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/draw.cpp.s
.PHONY : src/draw.cpp.s

src/executor.o: src/executor.cpp.o

.PHONY : src/executor.o

# target to build an object file
src/executor.cpp.o:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/executor.cpp.o
.PHONY : src/executor.cpp.o

src/executor.i: src/executor.cpp.i

.PHONY : src/executor.i

# target to preprocess a source file
src/executor.cpp.i:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/executor.cpp.i
.PHONY : src/executor.cpp.i

src/executor.s: src/executor.cpp.s

.PHONY : src/executor.s

# target to generate assembly for a file
src/executor.cpp.s:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/executor.cpp.s
.PHONY : src/executor.cpp.s

src/insn.o: src/insn.cpp.o

.PHONY : src/insn.o

# target to build an object file
src/insn.cpp.o:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/insn.cpp.o
.PHONY : src/insn.cpp.o

src/insn.i: src/insn.cpp.i

.PHONY : src/insn.i

# target to preprocess a source file
src/insn.cpp.i:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/insn.cpp.i
.PHONY : src/insn.cpp.i

src/insn.s: src/insn.cpp.s

.PHONY : src/insn.s

# target to generate assembly for a file
src/insn.cpp.s:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/insn.cpp.s
.PHONY : src/insn.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/translator.o: src/translator.cpp.o

.PHONY : src/translator.o

# target to build an object file
src/translator.cpp.o:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/translator.cpp.o
.PHONY : src/translator.cpp.o

src/translator.i: src/translator.cpp.i

.PHONY : src/translator.i

# target to preprocess a source file
src/translator.cpp.i:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/translator.cpp.i
.PHONY : src/translator.cpp.i

src/translator.s: src/translator.cpp.s

.PHONY : src/translator.s

# target to generate assembly for a file
src/translator.cpp.s:
	$(MAKE) -f CMakeFiles/int6502.dir/build.make CMakeFiles/int6502.dir/src/translator.cpp.s
.PHONY : src/translator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... int6502"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/executor.o"
	@echo "... src/executor.i"
	@echo "... src/executor.s"
	@echo "... src/insn.o"
	@echo "... src/insn.i"
	@echo "... src/insn.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/translator.o"
	@echo "... src/translator.i"
	@echo "... src/translator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

